---
config:
  layout: dagre
  theme: redux-color
title: Curso de Inglês
---

```mermaid
erDiagram
    ALUNO {
        string cpf PK
        string nome
        string sexo
        string endereco
    }

    INSTRUTOR {
        string cref PK
        string cpf
        string nome
        string sexo
        string endereco
    }

    AVALIACAO {
        int id PK
        string objetivo
        float altura
        float peso
        float imc
        date data
        string cpf_aluno FK
    }

    FICHA_TREINO {
        int idFicha PK
    }

    TREINO {
        int idTreino PK
        string nome
        string descricao
    }

    EXERCICIO {
        int idExercicio PK
        string nome
        int series
        int repeticoes
        float carga
    }

    ALUNO ||--o{ AVALIACAO : "realiza"
    ALUNO ||--|| FICHA_TREINO : "possui"
    INSTRUTOR ||--o{ ALUNO : "orienta"
    FICHA_TREINO ||--o{ TREINO : "possui"
    TREINO ||--o{ EXERCICIO : "contém"