---
config:
  layout: dagre
  theme: redux-color
title: BD Universidade
---
erDiagram
  direction TB
  COMPONENTE_CURRICULAR {
    int id PK
    string nome
    string tipo "Disciplina | Atividade"
    int departamento_id FK
    int curso_id FK
  }
  COMPONENTE_CURRICULAR ||--o{ REQUISITO : possui
  COMPONENTE_CURRICULAR ||--o{ TURMA : possui

  REQUISITO {
    int id PK
    int componente_id FK
    string descricao
  }

  DEPARTAMENTO {
    int id PK
    string nome
    string local
    int centro_id FK
  }
  DEPARTAMENTO ||--o{ COMPONENTE_CURRICULAR : responsavel
  DEPARTAMENTO ||--o{ DOCENTE : contem

  DOCENTE {
    int id PK
    string nome
    string titulacao
    int departamento_id FK
  }
  DOCENTE }o--o{ TURMA : leciona

  ALUNO {
    int matricula PK
    string nome
    int curso_id FK
  }
  ALUNO }o--o{ TURMA : frequenta
  ALUNO }o--o| MONITORIA : podeSerMonitor
  ALUNO ||--o{ AVALIACAO : possui

  MONITORIA {
    int id PK
    int aluno_id FK
    int turma_id FK
    string funcao
  }
  MONITORIA ||--|| TURMA : atuaEm
  MONITORIA ||--|| ALUNO : ehAluno

  TURMA {
    int id PK
    string semestre
    int componente_id FK
  }
  TURMA ||--o{ AVALIACAO : contem

  AVALIACAO {
    int id PK
    int aluno_id FK
    int turma_id FK
    float nota1
    float nota2
    float nota3
    string situacao "APROVADO | REPROVADO"
  }
  
  CENTRO ||--o{ CURSO : possui
  CENTRO ||--o{ DEPARTAMENTO : contem
  CURSO ||--o{ COMPONENTE_CURRICULAR : possui
  CURSO ||--o{ ALUNO : matricula