---
config:
  layout: dagre
  theme: redux-color
title: BD Universidade
---
erDiagram
  direction TB
  CENTRO {
        
  }
    
  DEPARTAMENTO {
    string codigo PK ""
    string sigla ""
    string nome ""
    string local ""
  }

  DOSCENTE {
    string siape PK ""
    string nome ""
    string formacao ""
    string area ""
  }

  TURMA {

  }

  DISCENTE {
    string matricula PK ""
    string nome ""
  }

  COMPONENTE_CURRICULAR {

  }
